### ISSUE TITLE
Data error!

### ISSUE THREAD

**Issue by happsky** [tgeorgy/mgan#2]
Hi, thank you for sharing this code, but when I executing 'sh init_data.sh', I got following error, may you provide a solution for me?

 extracting: img_align_celeba/202594.jpg  
 extracting: img_align_celeba/202595.jpg  
 extracting: img_align_celeba/202596.jpg  
 extracting: img_align_celeba/202597.jpg  
 extracting: img_align_celeba/202598.jpg  
 extracting: img_align_celeba/202599.jpg  
Traceback (most recent call last):
  File "crop_images.py", line 29, in <module>
    os.rename(ipath+fname, 'data/celeba/pos/'+fname)
OSError: [Errno 2] No such file or directory

**Comment by tgeorgy** [comment]
Hi, thank you for reporting this. It should work now.
