### ISSUE TITLE
Paper about this project

### ISSUE THREAD

**Issue by o0t1ng0o** [tgeorgy/mgan#3]
Hi, tgeorgy.

I really appreciate your work.
And i wonder whether u wrote any paper about this project?

Valentina

**Comment by tgeorgy** [comment]
Hi Valentina, thank you. I barely had time to run experiments and write an article about it, so no.

**Comment by zhangqianhui** [comment]
@tgeorgy  Recently, I am writing one paper about images translation, So are you interesting in joining us as one of authors? Because I found our model with your mask_gan has achieved very high-qulaity translation results.

**Comment by tgeorgy** [comment]
@zhangqianhui Sounds interesting, you can write me here - georgtrof at gmail.com

**Comment by zhangqianhui** [comment]
Sorry, the final ideas have not been decided. We need to do more experiments.
