### ISSUE TITLE
RuntimeError: input and target shapes do not match: input [1 x 1 x 1 x 1], target [1 x 1]

### ISSUE THREAD

**Issue by hondahmd** [tgeorgy/mgan#5]
Hi, tgeorgy.

I'v just started learning GAN and used your code for my first try. Unluckily I met a problem which I can't solve. At line 113 an error existed, where the code is:

`loss_P2N_gan = criterion_gan(fake_neg_lbl, Variable(real_lbl)).`

And the traceback is :

> RuntimeError: input and target shapes do not match: input [1 x 1 x 1 x 1], target [1 x 1]

It seems that the dimensions of the scalars differ from each other. Could you tell me how to solve the problem? Or what should I learn to handle this? I ran the code using python 3.6, so I changed the _'itertools.izip'_ to _'zip'_, does this affect the programme?

Best regards,
Hondahmd

**Comment by buaaswf** [comment]
Hi@ @hondahmd , I met the same problem, could you please tell me how to solve this

**Comment by hondahmd** [comment]
@buaaswf Sorry I didn't figure out a solution. But I believe that it might have something to do with your develop environment, your package version, for example.

**Comment by Fly2flies** [comment]
> @buaaswf Sorry I didn't figure out a solution. But I believe that it might have something to do with your develop environment, your package version, for example.

 I also have the same problem. As you said, it has something to do with the development environment version, as show below:
    input and target shapes do not match: input [1 x 1 x 1 x 1], target [1 x 1] at c:\programdata\miniconda3\condabld\pytorch_1533086611947\work\aten\src\thcunn\generic/MSECriterion.cu:12
So, have you solved it yet?

**Comment by miaoYuanyuan** [comment]
modify the line 71-74 in train.py  : 
`real_lbl=torch.zeros(batch_size,1,1,1).cuda()
real_lbl[:,0,0,0]=1
fake_lbl=torch.zeros(batch_size,1,1,1).cuda()
fake_lbl[:,0,0,0]=1
` @hondahmd

**Comment by hondahmd** [comment]
> modify the line 71-74 in train.py :
> `real_lbl=torch.zeros(batch_size,1,1,1).cuda() real_lbl[:,0,0,0]=1 fake_lbl=torch.zeros(batch_size,1,1,1).cuda() fake_lbl[:,0,0,0]=1 ` @hondahmd

Thx! It works!
